// vegetarianFastFoodArray
export const vegetarianFastFoodArray = [
    "Veggie Burger",
    "Veggie Wrap",
    "Vegetarian Pizza",
    "Veggie Nuggets",
    "Fries",
    "Onion Rings",
    "Mushroom Burger",
    "Grilled Cheese Sandwich",
    "Falafel",
    "Hummus Wrap",
    "Veggie Burrito",
    "Black Bean Burger",
    "Tofu Stir-Fry",
    "Sweet Potato Fries",
    "Veggie Tacos",
    "Caprese Panini",
    "Quinoa Salad",
    "Veggie Hot Dog",
    "Veggie Sushi Rolls",
    "Eggplant Parmesan",
    "Chickpea Salad",
    "Veggie Gyro",
    "Vegetable Lo Mein",
    "Broccoli Cheddar Bites",
    "Veggie Quesadilla",
    "Avocado Toast",
    "Cauliflower Wings",
    "Veggie Stir-Fry",
    "Spinach and Mushroom Pizza",
    "Veggie Pad Thai",
    "Bean and Rice Burrito",
    "Veggie Spring Rolls",
    "Veggie Nachos",
    "Pasta Primavera",
    "Tofu Burger",
    "Veggie Sausage",
    "Veggie Sushi Bowl",
    "Veggie Tofu Scramble",
    "Veggie Caesar Salad",
    "Stuffed Bell Peppers",
    "Veggie Gyoza",
    "Veggie Pho",
    "Veggie Biryani",
    "Zucchini Noodles",
    "Veggie Reuben Sandwich",
    "Veggie Calzone",
    "Veggie Pita Wrap",
    "Veggie Chili",
    "Veggie Empanadas",
    "Veggie Goulash",
    "Veggie Tikka Masala",
    "Veggie Soba Noodles",
    "Veggie Enchiladas",
    "Veggie Szechuan Tofu",
    "Veggie Scone",
    "Veggie Jambalaya",
    "Veggie Gumbo",
    "Veggie Tamales",
    "Veggie Lasagna",
];

// You now have an array of 60 vegetarian or vegan fast food items.
